### ISSUE TITLE
Часть 6. Cocotb

### ISSUE THREAD

**Issue by WoWaster** [Lamagraph/intro-to-fpga-with-clash#18]
Здесь про то как писать тесты более простым образом с помощью cocotb, потому что SV сложный. 
И ещё надо что-то рассказать про свёртку картинков, это к @gsvgit.

Упражнения:
* переписать старые тб на cocotb для разминки
* написать свёртку картинки, как раз можно будет взять [Pillow](https://github.com/python-pillow/Pillow)

**Comment by KubEF** [comment]
Интересная презентация на тему: https://indico.cern.ch/event/776422/attachments/1769690/2874927/cocotb_talk.pdf

**Comment by WoWaster** [comment]
> Интересная презентация на тему: https://indico.cern.ch/event/776422/attachments/1769690/2874927/cocotb_talk.pdf

API с 2018 похоже практически полностью устарело. Зато красивая success story. И в конце есть ссылка на более актуальные материалы

**Comment by WoWaster** [comment]
Красивое: https://rodrigomelo9.github.io/FOSS-for-FPGAs/cocotb.html#/
